(setq lista '(5 6 8 7 9))
(write lista)
(sort lista #'<)
(print"menor de la lista:")
(print(first lista))
(print "mayor de la lista:" )
(print(last lista))
(print "promedio de la lista: ")
(print (/(apply '+ lista ) (length lista) ))